import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globalStyles/globals.css";
import "./globalStyles/header.css";
import "./globalStyles/menu.css";
import Layout from "@/components/layouts/Layout";



const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight : ['300' , '500', '700', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable}`} style={{fontFamily: 'var(--font-rubik)'}}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
